### ISSUE TITLE
[Developer Experience] Missing/invalid signal/query makes the CLI simply return context canceld

### ISSUE THREAD

**Issue by macnibblet** [cludden/protoc-gen-go-temporal#83]
Sample Proto

```protobuf
service ContextCanceldExample {
  rpc DoSomething(google.protobuf.Empty) returns (google.protobuf.Empty) {
    option (temporal.v1.workflow) = {
      id: 'context-canceled-example',

      signal: {ref: "CancelWorkflow"},
    };
  }
}
```

**Current developer experience**
```bash
buf generate
Failure: context canceled
```

**Expected experience**
```bash
buf generate
Error: there is no matching rpc method for the signal CancelWorkflow in the workflow DoSomething
```

**Comment by cludden** [comment]
This should already be [handled](https://github.com/cludden/protoc-gen-go-temporal/blob/v1.14.3/internal/plugin/parse.go#L216-L238), and I haven't been able to replicate this issue, when I try:
```shell
Failure: plugin protoc-gen-go_temporal: workflow  "mycompany.simple.Simple.SomeWorkflow1" references undefined signal: "mycompany.simple.Simple.UndefinedSignal"
```
Can you provide any more details about your configuration (e.g. versions of buf, protoc-gen-go, protoc-gen-go-temporal)

**Comment by macnibblet** [comment]
Buf version: 1.48.0

```
protoc-gen-go --version
protoc-gen-go v1.34.2
```

```
protoc-gen-go_temporal --version
protoc-gen-go-temporal: dev
go: go1.23.2
```

buf.lock
```
# Generated by buf. DO NOT EDIT.
version: v2
deps:
  - name: buf.build/cludden/protoc-gen-go-temporal
    commit: 74c5da82fab44686aa2d1605f0f81d50
    digest: b5:4b8e6dcf9d594d1182cb7259b3346b7226a6cf185e01f28c1015a41dbb46c990f5612c1da3fb45dca8eebf5835e6a6b92986952d4973359bc613c6dd4a101340
  - name: buf.build/nvxx/protopatch
    commit: ef95e8420acb4e438d230a2f05895d78
    digest: b5:9850d3835fb74d7c4f9a3bbc656485602e7c1c25eaa98706b316c8af896db255aa1f9cb71d42a3656b200390b1e2c86d91bb8b7453775b921b46e47a0a031a23
```


buf.gen.yml
```
version: v2
managed:
  enabled: true
  disable:
    - file_option: go_package
      module: buf.build/cludden/protoc-gen-go-temporal

inputs:
  - module: buf.build/cludden/protoc-gen-go-temporal:main
  - directory: protobuf/

plugins:
  - remote: buf.build/protocolbuffers/go
    out: protobuf/
    opt: paths=source_relative

  - remote: buf.build/protocolbuffers/python
    out: src/python/protobuf/

  - remote: buf.build/protocolbuffers/pyi
    out: src/python/protobuf/

  - local: protoc-gen-go_temporal
    out: protobuf/
    opt: paths=source_relative,enable-patch-support=true
    strategy: all
```
